[tool.poetry]
name = "labuk"
version = "1.0.0"
description = "FastAPI project with JWT authentication"
authors = ["Anton Mazur <antonmazur1211@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.0"
uvicorn = "^0.34.0"
pydantic = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
